### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by dohliam** [polgfred/js1k#1]
Hi polgfred, thanks for sharing your js1k entry (this game is surprisingly addictive)! :+1: I notice you haven't included a license. Would it be possible to release this under a free license so that it can be included in the [openjs1k](https://github.com/dohliam/openjs1k) project? Even if you don't plan on using a free license, having a license of some kind would help people know whether or not they can reuse your work. :smile:

**Comment by polgfred** [comment]
Thanks! Yes, I've been told by many about the game's addictive properties. ;)

Absolutely, I'll add a license, and submit a pull request to openjs1k.
